version: '3'
services:
  mysql:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/bitnami/mysql/data

volumes:
  mysql_data: